spring.application.name=UrlService

spring.datasource.url=jdbc:postgresql://ep-polished-cake-a15tyzb1-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_dU7NuRS3fDMB&sslmode=require&channelBinding=require
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
